---

name: Publish

on:
  push:
    branches:
      - main
    paths:
      - applications/*.json

jobs:
  parse:
    name: Parse
    runs-on: ubuntu-latest

    outputs:
      rdnn: ${{ steps.parse.outputs.rdnn }}
      version: ${{ steps.parse.outputs.version }}
      source: ${{ steps.parse.outputs.source }}
      commit: ${{ steps.parse.outputs.commit }}
      end-of-life: ${{ steps.parse.outputs.end-of-life }}
      end-of-life-rebase: ${{ steps.parse.outputs.end-of-life-rebase }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Parse
        id: parse
        uses: elementary/action-appcenter-review-parse@v1.2.5
        with:
          regex: |
            applications\/(?<rdnn>[a-zA-Z0-9\.\-\_]+)\.json

  publish:
    name: Publish (${{ matrix.configuration.arch }})
    runs-on: ${{ matrix.configuration.runs-on }}
    needs: parse

    strategy:
      matrix:
        configuration:
          # FIXME: Remove flat-manager-suffix when we update to the container with flatpak-builder >= 1.4.6
          - arch: x86_64
            runs-on: ubuntu-latest
            flat-manager-suffix: amd64
            flat-manager-sha256: 9733a148ac185bc8d7fb0429a43f9ad7d934635760bb71933658642c697f87c9
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
            flat-manager-suffix: arm64
            flat-manager-sha256: fa9a916badc539ff7319895789f004dc99b81eb8e90a75857232121650335956
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      # mirror-screenshots-url option of flatpak-builder action requires flatpak-builder >= 1.4.6,
      # which is only available on questing or later, to use --compose-url-policy option internally
      # FIXME: Replace with newer version of our platform that based on resolute
      #image: ghcr.io/elementary/flatpak-platform/runtime:8-${{ matrix.configuration.arch }}
      image: ubuntu:resolute
      options: --privileged

    steps:
      # FIXME: Remove when we update to the container with flatpak-builder >= 1.4.6
      - name: Install dependencies
        run: |
          apt install -yU curl git flatpak-builder xvfb
          curl -L https://github.com/flatpak/flat-manager/releases/download/0.5.0/flat-manager-client.${{ matrix.configuration.flat-manager-suffix }} -o ./flat-manager-client
          CHKSUM=$(sha256sum ./flat-manager-client | awk '{ print $1 }')
          if [ "$CHKSUM" != "${{ matrix.configuration.flat-manager-sha256 }}" ]; then
            echo "flat-manager-client verify error! got $CHKSUM"
            exit 1
          fi
          mv ./flat-manager-client /usr/bin/flat-manager-client
          chmod +x /usr/bin/flat-manager-client

      - name: Checkout
        run: |
          git config --global --add safe.directory /__w/appcenter-reviews/appcenter-reviews
          git clone ${{ needs.parse.outputs.source }} .
          git checkout ${{ needs.parse.outputs.commit }}

      - name: Manifest
        id: manifest
        uses: elementary/action-appcenter-review-find-manifest@v1.5.1
        with:
          rdnn: ${{ needs.parse.outputs.rdnn }}

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.7
        with:
          bundle: ${{ needs.parse.outputs.rdnn }}.flatpak
          manifest-path: ${{ steps.manifest.outputs.manifest }}
          mirror-screenshots-url: https://flatpak.elementary.io/repo/screenshots
          run-tests: false
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          branch: stable
          cache-key: "flatpak-builder-${{ github.sha }}"
          arch: ${{ matrix.configuration.arch }}

      - name: Deploy
        uses: flatpak/flatpak-github-actions/flat-manager@v6.7
        with:
          repository: appcenter
          flat-manager-url: https://flatpak-api.elementary.io
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}
          end-of-life: "${{ needs.parse.outputs.end-of-life }}"
          end-of-life-rebase: ${{ needs.parse.outputs.end-of-life-rebase }}
